apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fastapi-app.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "fastapi-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  ingressClassName: {{ default "alb" .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "fastapi-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
